### PR TITLE
Bump Testcontainers to 0.31.0

### PR DESCRIPTION
**Pull request by vaihtovirta**
## References

Bumped version of testcontainers to 0.31.0 and adjusted the code with the changed contract of  `testcontainers.CustomizeRequestOption`

https://github.com/testcontainers/testcontainers-go/releases/tag/v0.31.0

> ⚠️ Breaking Changes
> break: return error from Customize request option (https://github.com/testcontainers/testcontainers-go/pull/2267) @stevenh

## Submitter checklist

- [ ] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [ ] The PR title represents the desired changelog entry
- [ ] The repository's code style is followed (see the contributing guide)
- [ ] Test coverage that demonstrates that the change works as expected
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks!

**Comment by syanukov** [comment]
> @oleg-nenashev what is the release schedule for the module? Is this PR something that can be added to the new release?
> 
> Thanks in advance

any update?

**Comment by oleg-nenashev** [comment]
Sorry, I was on vacation and muted GitHub. Will look into it this we

**Comment by ninadingole** [comment]
There is also a new release to v0.32.0 for testcontainers-go, could we please also add that in this PR and release this? I am also stuck because of this issue and had to copy the source to make things work. Thank you!

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the patch!

**Comment by oleg-nenashev** [comment]
Released in https://github.com/wiremock/wiremock-testcontainers-go/releases/tag/v1.0.0-alpha-9

**Pull request merged**
