### PR TITLE
Update dependencies: testcontainers & wiremock-go + Test against multiple recent Golang versions

### PR DESCRIPTION
**Pull request by AntoniKania**
## References
Direct dependencies updated:
testcontainers-go | `v0.22.0` => `v0.28.0`
go-wiremock | `v1.7.1` => `v1.8.0`
go-connections | `v0.4.0` => `v0.5.0`

I've also changed the minimal required version of go to the 1.20, as the new version of [testcontainers-go](https://github.com/testcontainers/testcontainers-go/blob/main/go.mod#L3) specifies this version. Docs that were specified the minimal version as 1.19 were also updated

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by jamietanna — APPROVED** [review]
I don't have commit access to this repo - but have some on the core Wiremock repo - and approve these changes.

The bump to Go 1.20 is required - to keep in line with the upstream requirement as you mention - and good that we're keeping vaguely in-date with Go versions.

I'd recommend us follow-up by testing against multiple versions (i.e. https://github.com/oapi-codegen/runtime/blob/1f1f11683f267893a4f7b2ab3c7ae000637e27ea/.github/workflows/ci.yml#L7-L22) to make sure that we're keeping support for newer versions of Go, too.

It may also be worth us making sure that the examples use `replace` directives to allow us to point to the current source checkout for the project, rather than pinning to whatever the latest released tag is, but that comes with a teency bit more complexity in your builds.

**Comment by jamietanna** [comment]
I'd also recommend this is merged as a `chore` :+1:

**Comment by AntoniKania** [comment]
Thanks for insightful comments and suggestions with sources!
I've applied the changes with CI/CD pipeline in this commit, and added the `chore:` prefix to the commit message.
I didn't quite get the suggestion with `replace` directives. Currently we are using them in two directories under the examples directory ([here](https://github.com/wiremock/wiremock-testcontainers-go/blob/main/examples/quickstart/go.mod#L44) and [here](https://github.com/wiremock/wiremock-testcontainers-go/blob/main/examples/using_api_client/go.mod#L46)), so that test files there could use the currently checkout code. Isn't it what you meant by your comment?

**Review by oleg-nenashev — APPROVED** [review]

**Comment by jamietanna** [comment]
Ah @AntoniKania I didn't mean for you to solve those additional things in this PR, was me talking out loud while I thought of it - appreciate the changes you did make!

**Pull request merged**
